/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
import { HttpResponse, http } from "msw";
import { faker } from "@faker-js/faker";
import { setupServer } from "msw/node";

faker.seed(1);

const baseURL = "https://petstore.swagger.io/v2";
const MAX_ARRAY_LENGTH = 20;

let i = 0;
const next = () => {
  if (i === Number.MAX_SAFE_INTEGER - 1) {
    i = 0;
  }
  return i++;
};

export const handlers = [
  http.post(`${baseURL}/pet/:petId/uploadImage`, () => {
    const resultArray = [[getUploadFile200Response(), { status: 200 }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.post(`${baseURL}/pet`, () => {
    const resultArray = [[null, { status: 405 }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.put(`${baseURL}/pet`, () => {
    const resultArray = [
      [null, { status: 400 }],
      [null, { status: 404 }],
      [null, { status: 405 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/pet/findByStatus`, () => {
    const resultArray = [
      [getFindPetsByStatus200Response(), { status: 200 }],
      [null, { status: 400 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/pet/findByTags`, () => {
    const resultArray = [
      [getFindPetsByTags200Response(), { status: 200 }],
      [null, { status: 400 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/pet/:petId`, () => {
    const resultArray = [
      [getGetPetById200Response(), { status: 200 }],
      [null, { status: 400 }],
      [null, { status: 404 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.post(`${baseURL}/pet/:petId`, () => {
    const resultArray = [[null, { status: 405 }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.delete(`${baseURL}/pet/:petId`, () => {
    const resultArray = [
      [null, { status: 400 }],
      [null, { status: 404 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.post(`${baseURL}/store/order`, () => {
    const resultArray = [
      [getPlaceOrder200Response(), { status: 200 }],
      [null, { status: 400 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/store/order/:orderId`, () => {
    const resultArray = [
      [getGetOrderById200Response(), { status: 200 }],
      [null, { status: 400 }],
      [null, { status: 404 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.delete(`${baseURL}/store/order/:orderId`, () => {
    const resultArray = [
      [null, { status: 400 }],
      [null, { status: 404 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/store/inventory`, () => {
    const resultArray = [[getGetInventory200Response(), { status: 200 }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.post(`${baseURL}/user/createWithArray`, () => {
    const resultArray = [[null, { status: NaN }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.post(`${baseURL}/user/createWithList`, () => {
    const resultArray = [[null, { status: NaN }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/user/:username`, () => {
    const resultArray = [
      [getGetUserByName200Response(), { status: 200 }],
      [null, { status: 400 }],
      [null, { status: 404 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.put(`${baseURL}/user/:username`, () => {
    const resultArray = [
      [null, { status: 400 }],
      [null, { status: 404 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.delete(`${baseURL}/user/:username`, () => {
    const resultArray = [
      [null, { status: 400 }],
      [null, { status: 404 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/user/login`, () => {
    const resultArray = [
      [getLoginUser200Response(), { status: 200 }],
      [null, { status: 400 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/user/logout`, () => {
    const resultArray = [[null, { status: NaN }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.post(`${baseURL}/user`, () => {
    const resultArray = [[null, { status: NaN }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
];

export function getUploadFile200Response() {
  return { code: 3767141444616192, type: "nisi", message: "terra" };
}

export function getFindPetsByStatus200Response() {
  return [
    {
      id: 4326942327177216,
      category: { id: 6351943247069184, name: "Ms. Doris Schneider" },
      name: "doggie",
      photoUrls: ["tactus", "adsidue", "acquiro", "universe"],
      tags: [
        { id: 5884243259424768, name: "Guadalupe O'Connell" },
        { id: 4438548025442304, name: "Nicolas Dare" },
        { id: 6571932990308352, name: "Elizabeth Vandervort" },
        { id: 8497387173576704, name: "Mr. Christopher Beahan MD" },
        { id: 8612960073154560, name: "Sylvia Windler" },
        { id: 8275169122451456, name: "Rufus Cremin" },
        { id: 1953016099897344, name: "Preston O'Keefe" },
        { id: 914270617337856, name: "Richard Bauch" },
        { id: 7366415793258496, name: "Wilbur Graham" },
        { id: 7759961574604800, name: "Marilyn Gusikowski" },
        { id: 8920027054997504, name: "Dr. Aubrey Lakin" },
        { id: 5926031057747968, name: "Leroy Moore" },
        { id: 5649948810936320, name: "Nelson Lang-Bauch" },
        { id: 4594994547523584, name: "Gregory Hagenes-Smitham" },
      ],
      status: "pending",
    },
    {
      id: 4973549448069120,
      category: { id: 8654755559636992, name: "Darin Gerhold" },
      name: "doggie",
      photoUrls: [
        "iure",
        "casus",
        "tumultus",
        "cohibeo",
        "accusantium",
        "constans",
      ],
      tags: [
        { id: 5999069591764992, name: "Diane Conroy" },
        { id: 10372155179008, name: "Howard Ortiz PhD" },
        { id: 7364580669915136, name: "Doris Glover" },
        { id: 7769944974426112, name: "Mr. Brian Jaskolski" },
        { id: 1303556407689216, name: "Georgia Blanda" },
        { id: 4532336727162880, name: "Roger Spinka" },
        { id: 8800650003480576, name: "Caroline Thiel" },
        { id: 2582620095381504, name: "Otis Reichert" },
        { id: 3659111522631680, name: "Miss Kayla Kerluke" },
        { id: 1912016637788160, name: "Conrad Schmeler" },
        { id: 625252461707264, name: "Estelle Harris" },
        { id: 3500349063168000, name: "Beth Tremblay" },
        { id: 7472550688849920, name: "Veronica Gutkowski-Dare" },
        { id: 4775815363428352, name: "Elvira Marvin" },
        { id: 3926358595993600, name: "Sheila Miller" },
        { id: 7029383598440448, name: "Gertrude Brekke" },
        { id: 7200512128581632, name: "Alison Mosciski" },
        { id: 5747290320928768, name: "Douglas Considine" },
        { id: 2055343620227072, name: "Yolanda Senger" },
      ],
      status: "sold",
    },
    {
      id: 2394315678547968,
      category: { id: 6023850953277440, name: "Harvey Pollich" },
      name: "doggie",
      photoUrls: ["brevis", "adfero", "ipsum", "alo", "timor", "caelum"],
      tags: [
        { id: 4235842539225088, name: "Lorenzo Daniel" },
        { id: 8349667024699392, name: "Adam Hoppe" },
        { id: 4702887382876160, name: "Cedric Lind" },
        { id: 4703198321311744, name: "Kristen Nolan" },
        { id: 3314804294942720, name: "Horace Miller-Dietrich" },
        { id: 6753422938210304, name: "Leonard Veum" },
        { id: 7319296583663616, name: "Salvatore Beahan" },
        { id: 8783472271294464, name: "Lynne Hauck" },
        { id: 7275437346521088, name: "Ms. Julia Kuhic" },
        { id: 5343150415544320, name: "Sarah Hilpert" },
        { id: 2468349105668096, name: "Emanuel Schowalter" },
        { id: 6265770294116352, name: "Kristine Klocko IV" },
        { id: 1597783429611520, name: "Kerry Mann" },
      ],
      status: "pending",
    },
    {
      id: 2397170563022848,
      category: { id: 7770550980050944, name: "Lauren Dare" },
      name: "doggie",
      photoUrls: [
        "defluo",
        "cuppedia",
        "stella",
        "sursum",
        "alii",
        "teres",
        "temperantia",
        "aequitas",
        "coniecto",
      ],
      tags: [
        { id: 5969237885583360, name: "Walter Waters" },
        { id: 1037583104606208, name: "Roger Rempel" },
      ],
      status: "sold",
    },
    {
      id: 78672333635584,
      category: { id: 5147735732781056, name: "Ervin Bradtke" },
      name: "doggie",
      photoUrls: [
        "aspernatur",
        "aveho",
        "quae",
        "spes",
        "caritas",
        "coma",
        "vespillo",
        "balbus",
      ],
      tags: [
        { id: 3681914275758080, name: "Dana Wintheiser" },
        { id: 7626044309766144, name: "Stanley Osinski" },
        { id: 7553686207201280, name: "Lynn Reichel" },
        { id: 1391874032009216, name: "Clara Stark Jr." },
        { id: 2092418008612864, name: "Pearl Padberg IV" },
        { id: 5337991050428416, name: "Marie Wolf-Kris" },
        { id: 3258555503214592, name: "Victor Hegmann" },
        { id: 4599158346350592, name: "Alberta Steuber" },
        { id: 2731081946103808, name: "Elias Koepp" },
        { id: 1379429653676032, name: "Blanche Bogisich" },
      ],
      status: "sold",
    },
    {
      id: 1643895333060608,
      category: { id: 5651362742272000, name: "Dr. Cory Mosciski Jr." },
      name: "doggie",
      photoUrls: ["tempora"],
      tags: [
        { id: 720022638952448, name: "Darnell Jast" },
        { id: 98933365800960, name: "Mr. Fred Schinner" },
        { id: 6448811979309056, name: "Latoya Hamill PhD" },
        { id: 8917775831531520, name: "Alan Kuhlman" },
        { id: 3777896839643136, name: "Alfred Ernser" },
        { id: 3009545548857344, name: "Ramon Torphy" },
        { id: 7869233094459392, name: "Sophia Dibbert" },
        { id: 2310934620012544, name: "Fred Cassin" },
        { id: 2599095814324224, name: "Nichole Mertz" },
      ],
      status: "sold",
    },
    {
      id: 735551946752000,
      category: { id: 5010107391803392, name: "Edmund Hayes" },
      name: "doggie",
      photoUrls: [
        "aestivus",
        "tristis",
        "substantia",
        "peccatus",
        "altus",
        "cicuta",
        "adinventitias",
        "trucido",
        "creo",
        "coruscus",
        "id",
        "alioqui",
        "denuncio",
        "veritas",
        "mollitia",
      ],
      tags: [
        { id: 2969043554271232, name: "Sherri Kerluke II" },
        { id: 4787185840553984, name: "Essie Rogahn" },
        { id: 3433511889403904, name: "Lisa Harris" },
        { id: 5624902518308864, name: "Hilda Bogisich" },
        { id: 8758742073999360, name: "Olivia Daugherty" },
        { id: 1175831103668224, name: "Lorraine Lueilwitz" },
        { id: 3017188558503936, name: "Miss Marcella Christiansen II" },
        { id: 2706685506355200, name: "Isaac Stehr" },
        { id: 2807171532193792, name: "Suzanne Effertz" },
        { id: 2198470169460736, name: "Todd Kautzer" },
        { id: 1836758960439296, name: "Ruben Bednar" },
        { id: 2580723022168064, name: "Kirk Reynolds" },
        { id: 8111160417058816, name: "Winston Hansen III" },
        { id: 6833964004147200, name: "Melinda Donnelly" },
        { id: 3015708214558720, name: "Simon Prohaska" },
        { id: 5293307028570112, name: "Jerry Pollich" },
        { id: 4190660286480384, name: "Rogelio Harris" },
        { id: 5784122991575040, name: "Katherine Green" },
      ],
      status: "sold",
    },
    {
      id: 7864801558528000,
      category: { id: 3936351659491328, name: "Tammy Beahan" },
      name: "doggie",
      photoUrls: [
        "contego",
        "defendo",
        "arx",
        "stabilis",
        "callide",
        "blandior",
        "volo",
        "capio",
        "pecto",
        "ars",
        "truculenter",
        "subnecto",
        "cras",
      ],
      tags: [
        { id: 7005673099362304, name: "Sara Bechtelar" },
        { id: 8343043803447296, name: "Jan Barrows" },
        { id: 8968184541478912, name: "Della Waters" },
        { id: 3691502962212864, name: "Mr. Larry Heathcote" },
        { id: 4481702957154304, name: "Rudolph Swift-Hackett IV" },
        { id: 2382549772926976, name: "Mack Wehner" },
        { id: 6084101442371584, name: "Kellie Ward" },
        { id: 7721075431440384, name: "Jill Champlin" },
        { id: 5182967131406336, name: "Julio Rohan" },
        { id: 1510186143449088, name: "Laurie Swift MD" },
        { id: 7178827245551616, name: "Israel Reichert" },
        { id: 6614691015032832, name: "Dr. Kathy Gusikowski" },
        { id: 5156113592877056, name: "Josephine Kutch" },
        { id: 5252206481637376, name: "Sidney White" },
        { id: 5366273844183040, name: "Paul Casper" },
        { id: 1063068641525760, name: "Miss Pearl Effertz" },
        { id: 6261708054069248, name: "Crystal Purdy" },
      ],
      status: "available",
    },
    {
      id: 8373794552938496,
      category: { id: 1137088600735744, name: "Gilbert Schiller" },
      name: "doggie",
      photoUrls: [
        "alioqui",
        "paulatim",
        "totam",
        "vulgaris",
        "delicate",
        "nostrum",
      ],
      tags: [
        { id: 2010173853925376, name: "Johnnie Koch" },
        { id: 4800825924780032, name: "Misty Bogisich" },
        { id: 1644670528520192, name: "Robin McLaughlin" },
        { id: 608120002838528, name: "Iris Kunze" },
        { id: 8614119332642816, name: "Judith Powlowski" },
        { id: 6283284518535168, name: "Kent Brown" },
        { id: 3984840183513088, name: "Grace Jacobi" },
        { id: 7161399578984448, name: "Kristi Steuber" },
        { id: 1157061847023616, name: "Mrs. Ellen McCullough DDS" },
        { id: 2146577084841984, name: "Danielle Toy DVM" },
        { id: 672466147999744, name: "Shawna Brakus" },
        { id: 3932636930113536, name: "Amelia Frami" },
        { id: 4675826343739392, name: "Gene Schimmel" },
        { id: 4120802771337216, name: "Molly Hickle" },
        { id: 8096414598955008, name: "Brandy Kemmer" },
        { id: 966491597963264, name: "Willie Emmerich" },
      ],
      status: "sold",
    },
    {
      id: 8457962695688192,
      category: { id: 5862903877992448, name: "Cora Blanda" },
      name: "doggie",
      photoUrls: [
        "callide",
        "vester",
        "delibero",
        "averto",
        "cerno",
        "ante",
        "adopto",
        "quisquam",
        "conservo",
        "cubo",
        "bos",
        "qui",
        "tabula",
        "aperiam",
        "nulla",
      ],
      tags: [
        { id: 1617496503222272, name: "Lowell Harris" },
        { id: 2595494897385472, name: "Jody Schinner" },
        { id: 7011881193570304, name: "Jaime Little" },
        { id: 8739026301353984, name: "Felipe Mann" },
        { id: 3892005088264192, name: "Darren Stark" },
        { id: 5222803504627712, name: "Devin Williamson" },
        { id: 2958953847717888, name: "Benjamin Mueller" },
        { id: 6190565949440000, name: "Willis Vandervort" },
        { id: 2927661999456256, name: "Vicki Torphy" },
        { id: 7627866523041792, name: "Flora Krajcik" },
        { id: 7700405874065408, name: "Cecelia Wiza" },
        { id: 3752331352997888, name: "Gerard Konopelski" },
        { id: 7109773220642816, name: "Dr. Stewart Brown" },
        { id: 1236652471091200, name: "Mr. Clint Bradtke" },
        { id: 116642879111168, name: "Lionel Halvorson" },
        { id: 5195945390112768, name: "Jenny Mueller" },
        { id: 233974672654336, name: "Ismael Deckow" },
        { id: 7151223796924416, name: "Ramona Spencer" },
      ],
      status: "available",
    },
    {
      id: 6034873873596416,
      category: { id: 1555858301386752, name: "Jenny Douglas" },
      name: "doggie",
      photoUrls: ["desolo", "currus", "una", "delibero"],
      tags: [
        { id: 5738743117905920, name: "Bethany Jakubowski" },
        { id: 3597156535500800, name: "Ellis Lemke III" },
        { id: 4578159137652736, name: "Dwight Marquardt" },
        { id: 8963131527135232, name: "Barry Halvorson II" },
        { id: 2735778518007808, name: "Luz Abshire" },
        { id: 1879825425891328, name: "Rudolph Schuppe" },
        { id: 630441866428416, name: "Thelma Kreiger" },
      ],
      status: "available",
    },
    {
      id: 1736702093688832,
      category: { id: 1154386931744768, name: "Laura Toy DDS" },
      name: "doggie",
      photoUrls: [
        "thermae",
        "adaugeo",
        "stips",
        "abscido",
        "veritas",
        "pecco",
        "cumque",
        "cursim",
        "angelus",
        "cui",
        "acies",
        "terga",
        "pauper",
        "aggredior",
      ],
      tags: [
        { id: 4205570649227264, name: "Reginald Maggio" },
        { id: 809075226968064, name: "Dawn Crooks" },
        { id: 8207754307043328, name: "Cory Howe MD" },
        { id: 4525885724033024, name: "Becky Abernathy" },
        { id: 6730770687197184, name: "Jane Block" },
        { id: 4012664562909184, name: "Henrietta Fisher" },
        { id: 8613780938293248, name: "Juan Hettinger" },
        { id: 6169016152358912, name: "Erika Torp-Skiles" },
        { id: 3771902157914112, name: "Rolando Jast" },
        { id: 6210233806356480, name: "Susan Haag" },
        { id: 776806990872576, name: "Maureen Schmidt" },
      ],
      status: "pending",
    },
    {
      id: 2343709926490112,
      category: { id: 4910581746237440, name: "Ms. Wendy Pfeffer" },
      name: "doggie",
      photoUrls: ["aegre", "libero", "acquiro", "cotidie", "conservo"],
      tags: [
        { id: 5744134715342848, name: "Shannon Medhurst III" },
        { id: 4253544647491584, name: "Darin Stoltenberg" },
        { id: 8800745147072512, name: "Janet Labadie" },
        { id: 493568196083712, name: "Eunice Dietrich" },
        { id: 4745284804411392, name: "Donald Schoen" },
        { id: 6757513150070784, name: "Leonard Schuster" },
        { id: 527008983416832, name: "Emmett Klocko" },
        { id: 3689402802896896, name: "Kate Schinner III" },
        { id: 923599974170624, name: "Ann Bednar" },
      ],
      status: "pending",
    },
    {
      id: 6640782761000960,
      category: { id: 5720843288051712, name: "Dr. Leticia Bogan" },
      name: "doggie",
      photoUrls: [
        "coniuratio",
        "demo",
        "coerceo",
        "ab",
        "audentia",
        "ultio",
        "arbustum",
        "celebrer",
        "sumptus",
        "communis",
        "delinquo",
        "vulnus",
        "conventus",
        "conqueror",
        "comis",
      ],
      tags: [
        { id: 3400989459611648, name: "Dolores Bailey-Hintz" },
        { id: 4070172681830400, name: "Jesus Beier" },
        { id: 8513631891226624, name: "Leland Hyatt" },
        { id: 3661066512891904, name: "Miss Evelyn Jacobs I" },
        { id: 1455725427556352, name: "Ted Yost" },
        { id: 6303709640261632, name: "Mr. Eric Abbott" },
        { id: 5115369884745728, name: "Bobby Kirlin" },
        { id: 6730622106075136, name: "Marcia Kiehn" },
        { id: 1541478740393984, name: "Garry Fisher" },
        { id: 2462605731954688, name: "Fernando Feil" },
        { id: 1525618653003776, name: "Dana Pacocha" },
        { id: 4708394984275968, name: "Dexter Dickinson" },
      ],
      status: "sold",
    },
  ];
}

export function getFindPetsByTags200Response() {
  return [
    {
      id: 6907811497771008,
      category: { id: 6059667165806592, name: "Wade Goldner" },
      name: "doggie",
      photoUrls: [
        "calco",
        "odio",
        "xiphias",
        "tubineus",
        "tergo",
        "absorbeo",
        "verumtamen",
        "suffragium",
        "vigor",
      ],
      tags: [
        { id: 4370065145200640, name: "Rosie Schumm-McLaughlin II" },
        { id: 4523776232390656, name: "Christina Runolfsdottir" },
      ],
      status: "sold",
    },
    {
      id: 7260152329666560,
      category: { id: 6272611256369152, name: "Ms. Hope Murazik MD" },
      name: "doggie",
      photoUrls: [
        "vitium",
        "deserunt",
        "amissio",
        "suggero",
        "vapulus",
        "dolor",
        "sol",
        "compello",
        "alo",
        "beatus",
        "culpo",
        "adicio",
        "tolero",
        "ipsam",
        "vito",
        "defleo",
        "utor",
        "surculus",
        "creator",
      ],
      tags: [
        { id: 1255559053443072, name: "Angelina Greenholt" },
        { id: 2695226076430336, name: "Leland Macejkovic III" },
        { id: 3788826623344640, name: "Sergio Braun-Schmidt III" },
        { id: 4975350920511488, name: "Inez Rice" },
        { id: 1355336676016128, name: "Andres Halvorson" },
        { id: 2339963379122176, name: "Latoya Harvey-Stamm" },
        { id: 74422046162944, name: "Sheryl Hintz" },
        { id: 8497997962805248, name: "Dr. Geneva Stiedemann IV" },
        { id: 2483803236859904, name: "Bridget Block" },
        { id: 4051369652649984, name: "Katherine Greenfelder" },
        { id: 1880300887998464, name: "Jessie Stark" },
        { id: 3224144156033024, name: "Ellen Barton" },
        { id: 4117358339686400, name: "Paulette Boyle" },
        { id: 7547536252338176, name: "Damon Lind" },
        { id: 4155979312660480, name: "Joel Gerhold" },
        { id: 266911052988416, name: "Chester Pagac" },
        { id: 5742659014492160, name: "Christina Padberg" },
      ],
      status: "sold",
    },
  ];
}

export function getGetPetById200Response() {
  return {
    id: 8024476694347776,
    category: { id: 6390405945884672, name: "Marty Hessel I" },
    name: "doggie",
    photoUrls: ["conitor", "caries"],
    tags: [
      { id: 8968156078931968, name: "Shawna Boyer" },
      { id: 4170483247349760, name: "Gilbert Mitchell" },
      { id: 3927538613092352, name: "Lula Barton" },
      { id: 6042259082444800, name: "Anne Ankunding" },
      { id: 6152357570150400, name: "Lauren Johnson" },
      { id: 6798308991303680, name: "Doreen Klocko" },
      { id: 709338714865664, name: "Kyle Adams" },
      { id: 2293889700462592, name: "Lydia Harris" },
      { id: 2479482623492096, name: "Miss Violet Murazik" },
      { id: 3163029191524352, name: "Ms. Yvonne Wehner I" },
      { id: 4528809862758400, name: "Conrad McLaughlin" },
      { id: 1803715667296256, name: "Jamie Stamm Jr." },
      { id: 4132626138923008, name: "Van Williamson" },
      { id: 3549045630959616, name: "Drew Koch" },
    ],
    status: "pending",
  };
}

export function getPlaceOrder200Response() {
  return {
    id: 6435709300768768,
    petId: 1125954252439552,
    quantity: 3231607127277568,
    shipDate: "2023-07-10T20:56:30.915Z",
    status: "delivered",
    complete: false,
  };
}

export function getGetOrderById200Response() {
  return {
    id: 5453177646219264,
    petId: 5247743882690560,
    quantity: 6872706630811648,
    shipDate: "2023-12-11T15:37:59.284Z",
    status: "approved",
    complete: true,
  };
}

export function getGetInventory200Response() {
  return {
    repellendus: 1989160581726208,
    succurro: 6182250733371392,
    creo: 4177146660519936,
    valeo: 5428363189551104,
    depraedor: 746276398301184,
  };
}

export function getGetUserByName200Response() {
  return {
    id: 8958617967394816,
    username: "Emilio Sanford",
    firstName: "Kenny Bayer",
    lastName: "Tiffany Homenick",
    email: "Everett_Leuschke75@yahoo.com",
    password: "vester",
    phone: "tibi",
    userStatus: 8622389277491200,
  };
}

export function getLoginUser200Response() {
  return "velut";
}

// This configures a Service Worker with the given request handlers.
export const startWorker = () => {
  const server = setupServer(...handlers);
  server.listen();
};
